[package]
name = "os"
version = "0.1.0"
edition = "2021"

[profile.release]
# lto = "thin"
debug = true
opt-level = 0

[dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
sys = { path = "../sys" }
bitflags = "2.5.0"
