[package]
name = "os"
version = "0.1.0"
edition = "2021"

[profile.release]
# lto = "thin"
debug = true
opt-level = 0

[dependencies]
sbi-rt = { version = "0.0.2", features = ["legacy"] }
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
