#[allow(dead_code)]
enum SyscallIndex {
    SYSFORK     = 1,
    SYSEXIT     = 2,
    SYSWAIT     = 3,
    SYSPIPE     = 4,
    SYSREAD     = 5,
    SYSKILL     = 6,
    SYSEXEC     = 7,
    SYSFSTAT    = 8,
    SYSCHDIR    = 9,
    SYSDUP      = 10,
    SYSGETPID   = 11,
    SYSSBRK     = 12,
    SYSSLEEP    = 13,
    SYSUPTIME   = 14,
    SYSOPEN     = 15,
    SYSWRITE    = 16,
    SYSMKNOD    = 17,
    SYSUNLINK   = 18,
    SYSLINK     = 19,
    SYSMKDIR    = 20,
    SYSCLOSE    = 21,
    SYSSHUTDOWN = 22,
}
